eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance: #处理eureka的自我保护机制
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2

server:
  port: 8765
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true
